# Barkley parameter ---------------------------
a: 0.75
b: 0.06
epsilon: 0.08
alpha: 3

# Simulation quanities ------------------------

starting_condition: chaotic # two_spirals, chaotic
dt: 0.01
ds: 0.1
D: 0.02 
size: [120,120,120] # Cube size

# Save settings -------------------------------

dSave: 16 # Sequence discretization for saving in [*ds]
max_save_length: 512 # Sequence length
num_sims: 1 # How many independent simulation with one call
dataset: regimeB
#save_folder: /home/roland/Projekte/FromSurface2Depth/data/raw/regimeB
#save_folder: /data.bmp/stenger/FromSurface2Depth/data/spirals/raw
